name: Build

on:
    push:
        branches:
            - main
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18
            - name: Install Yarn
              run: npm install -g yarn
            - name: Install dependencies
              run: yarn install
            - name: Build app
              run: yarn build
            - name: Set up Git
              run: 
                git config --global user.email "praxive@sdevs.org" 
                git config --global user.name "Praxive"
            - name: Commit changes
              run: git add . && git commit -m "Browser Build $(date)"
            - name: Push changes
              run: git push